export default {
  login: "devsamir",
  id: 56377354,
  node_id: "MDQ6VXNlcjU2Mzc3MzU0",
  avatar_url: "https://avatars2.githubusercontent.com/u/56377354?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/devsamir",
  html_url: "https://github.com/devsamir",
  followers_url: "https://api.github.com/users/devsamir/followers",
  following_url: "https://api.github.com/users/devsamir/following{/other_user}",
  gists_url: "https://api.github.com/users/devsamir/gists{/gist_id}",
  starred_url: "https://api.github.com/users/devsamir/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/devsamir/subscriptions",
  organizations_url: "https://api.github.com/users/devsamir/orgs",
  repos_url: "https://api.github.com/users/devsamir/repos",
  events_url: "https://api.github.com/users/devsamir/events{/privacy}",
  received_events_url: "https://api.github.com/users/devsamir/received_events",
  type: "User",
  site_admin: false,
  name: "Samir Batoq",
  company: null,
  blog: "samirbatoq.com",
  location: "Indonesia",
  email: null,
  hireable: null,
  bio:
    "A Full Stack Javascript Developer MERN Stack (Mysql, Express, React, Nodejs)",
  twitter_username: null,
  public_repos: 5,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2019-10-10T03:22:09Z",
  updated_at: "2020-08-11T13:10:28Z",
};
